const app=document.getElementById("app");
const blocks=[
{name:"Warm-up & Movement",minutes:12,sets:"2",reps:"",partner:"individual/pair",focus:"movement, balance, ukemi"},
{name:"Technical Development",minutes:25,sets:"4",reps:"6",partner:"pair",focus:"quality entries and controlled repetitions"},
{name:"Decision / Constraint Block",minutes:18,sets:"3",reps:"4",partner:"pair",focus:"setup quality -> selection precision"},
{name:"Randori Transfer",minutes:20,sets:"4",reps:"2 min",partner:"rotation",focus:"apply decision under pressure"},
{name:"Osaekomi / Cooldown",minutes:10,sets:"2",reps:"",partner:"pair/individual",focus:"control, recovery, reflection"}
];
function field(label,id,value,type){return '<div class="field"><label>'+label+'</label><input id="'+id+'" type="'+(type||"text")+'" value="'+String(value||"").replace(/"/g,"&quot;")+'"></div>'}
function render(){
let b="";
blocks.forEach(function(x,i){b+='<div class="block"><b>'+x.name+'</b>'+field("Minutes","m"+i,x.minutes,"number")+field("Sets","s"+i,x.sets)+field("Reps / Round","r"+i,x.reps)+field("Partner System","p"+i,x.partner)+field("Execution Focus","f"+i,x.focus)+'<button onclick="done('+i+')">Mark Completed</button></div>'});
app.innerHTML='<header class="top"><div><b>KAIZO TRAINING</b><div>Training Session Execution Workspace · Core preserved</div></div><div id="status">DRAFT</div></header><main class="wrap"><div class="grid"><section class="card span-12"><h2>Session Control</h2><div class="row">'+field("Session ID","sid","SES-"+Date.now())+field("Date","date",new Date().toISOString().slice(0,10),"date")+field("Group","group","U11")+field("Phase","phase","Development")+field("Primary Objective","objective","Improve decision quality under randori pressure")+'</div><div class="notice"><b>Coach Final Authority:</b> this workspace structures execution; it does not make the final coaching decision. Draft data is local and non-authoritative.</div></section><section class="card span-8"><h2>Execution Blocks</h2><div id="blocks">'+b+'</div></section><section class="card span-4"><h2>Live Checklist</h2><div class="checklist"><label class="check"><input type="checkbox" data-c="attendance"> Attendance confirmed</label><label class="check"><input type="checkbox" data-c="safety"> Safety / mat readiness</label><label class="check"><input type="checkbox" data-c="objective"> Objective explained</label><label class="check"><input type="checkbox" data-c="dose"> Dose adjusted by coach</label><label class="check"><input type="checkbox" data-c="pressure"> Pressure introduced</label><label class="check"><input type="checkbox" data-c="transfer"> Randori transfer observed</label></div><button onclick="completeSession()">Complete Session</button><pre id="completion" class="output"></pre></section><section class="card span-8"><h2>KPI & Retest</h2><div class="row">'+field("KPI","kpi","appropriate attacks / 5 randori entries")+field("Observed","observed","")+field("Retest","retest","same constraint, independent round")+'</div><label>Coach Notes</label><textarea id="notes" style="width:100%" placeholder="What changed? What should be repeated differently?"></textarea></section><section class="card span-4"><h2>Session Summary</h2><pre id="summary" class="output"></pre></section></div></main>';
sync();
}
function sync(){var data={session_id:document.getElementById("sid").value,group:document.getElementById("group").value,objective:document.getElementById("objective").value,blocks:blocks,kpi:document.getElementById("kpi").value,observed:document.getElementById("observed").value,retest:document.getElementById("retest").value,coach_final_authority:true,authoritative_record:false};document.getElementById("summary").textContent=JSON.stringify(data,null,2)}
function done(i){blocks[i].status="Completed";sync()}
function completeSession(){var missing=[...document.querySelectorAll("[data-c]")].filter(function(x){return !x.checked}).map(function(x){return x.dataset.c});var completed=blocks.filter(function(x){return x.status==="Completed"}).length;var r={completed_blocks:completed,total_blocks:blocks.length,missing_checklist:missing,status:missing.length===0&&completed===blocks.length?"READY_FOR_CLOSE":"INCOMPLETE",coach_final_authority:true,authoritative_record:false};document.getElementById("completion").textContent=JSON.stringify(r,null,2);document.getElementById("status").textContent=r.status}
render();